#!/usr/bin/env python3
"""Generate an automotive-inspired README from the approved static artwork."""
from pathlib import Path
from html import escape
import base64
from PIL import Image
ROOT=Path(__file__).resolve().parent
OUT=ROOT/'assets'/'porsche'
OWNER='EXID-Developer'
U=f'https://github.com/{OWNER}'
VIEWS={
 'hero':(0,58,1536,380),
 'stack':(0,438,1024,510),
 'connect':(1024,438,512,88),
 'github':(1024,526,512,80),
 'repositories':(1024,606,512,80),
 'stars':(1024,686,512,100),
 'dial':(1024,786,512,162),
 'footer':(0,948,1536,76),
}
LABELS={'hero':'Think with your code. EXID-Developer. Java, Spring Boot, React, Spring AI.',
 'stack':'Tech Stack — Backend: Java, Spring Boot, MyBatis. Frontend: TypeScript, React, Vite. AI & Tools: Spring AI, Git.',
 'connect':'Connect','github':'GitHub profile','repositories':'Repositories','stars':'Stars',
 'dial':'Build. Refine. Repeat.','footer':'Code with precision.'}
def effects(x,y,w,h):
 return f'''<defs><linearGradient id="shine"><stop stop-color="white" stop-opacity="0"/><stop offset=".5" stop-color="white" stop-opacity=".13"/><stop offset="1" stop-color="white" stop-opacity="0"/></linearGradient></defs><style>@keyframes sweep{{0%,15%{{transform:translateX(-{w}px)}}85%,100%{{transform:translateX({w*2}px)}}}}.shine{{animation:sweep 9s ease-in-out infinite}}@media(prefers-reduced-motion:reduce){{.shine{{animation:none;opacity:0}}}}</style><g style="pointer-events:none"><rect class="shine" x="{x-w}" y="{y}" width="{w//3}" height="{h}" fill="url(#shine)"/><path d="M {x+12} {y+h-2} H {x+w-12}" stroke="#ea4444" stroke-opacity=".5"/></g>'''
def build():
 OUT.mkdir(exist_ok=True)
 im=Image.open(OUT/'approved-design.webp')
 if im.size!=(1536,1024):raise ValueError(f'Unexpected artwork dimensions {im.size}')
 b64=base64.b64encode((OUT/'approved-design.webp').read_bytes()).decode()
 for key,(x,y,w,h) in VIEWS.items():
  svg=f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="{x} {y} {w} {h}" role="img"><title>{escape(LABELS[key])}</title><image width="1536" height="1024" href="data:image/webp;base64,{b64}"/>{effects(x,y,w,h)}</svg>'
  (OUT/f'{key}.svg').write_text(svg)
 from porsche_panels import build_panels
 build_panels()
 print('Built automotive theme assets')
def image(key,width='100%'):
 return f'<img src="./assets/porsche/{key}.svg" width="{width}" alt="{escape(LABELS[key])}"/>'
def switches():
 out=[]
 for label,key,col in [('AUTO','auto','8FD3FF'),('ELYSIUM','elysium','F5D78E'),('CYBERPUNK','cyberpunk','FF2BD6'),('PORSCHE','porsche','D73636')]:
  url=f'{U}/{OWNER}/issues/new?title=theme%3A{key}&body=Submit+to+switch+the+profile+theme.'
  out.append(f'<a href="{url}"><img src="https://img.shields.io/badge/{label}-'+('active' if key=='porsche' else 'switch')+f'-{col}?style=flat-square&amp;labelColor=17191D" alt="{label}"/></a>')
 return ' '.join(out)
def render():
 cards='bg_color=111315&border_color=44484C&title_color=F2F2F2&icon_color=D73636&text_color=BFC3C7'
 pins=[]
 for repo in ['damso','SpringAiBasic','sivertown','SpringBootMyBatis']:
  pins.append(f'<a href="{U}/{repo}"><img src="./assets/porsche/project-{repo}.svg" width="49%" alt="{repo} — open repository"/></a>')
 s=f'''<!-- Generated by porsche.py via build_readme.py. -->
<p align="right"><a href="#profile">PROFILE</a> · <a href="#projects">PROJECTS</a> · <a href="#stack">STACK</a></p>

<a name="profile"></a>

<a href="./assets/porsche/hero-film.mp4"><picture><source media="(prefers-reduced-motion: reduce)" srcset="./assets/porsche/hero.svg"/><img src="./assets/porsche/hero-motion.webp" width="100%" alt="Think with your code — cinematic Porsche-inspired profile. Click to open MP4."/></picture></a>

<p align="right"><a href="./assets/porsche/hero-film.mp4">▶ WATCH FILM · MP4</a></p>

<a name="stack"></a>

<table width="100%"><tr>
<td width="66%" valign="top">{image('stack')}</td>
<td width="34%" valign="top">
{image('connect')}<br/>
<a href="{U}">{image('github')}</a><br/>
<a href="{U}?tab=repositories">{image('repositories')}</a><br/>
<a href="{U}?tab=stars">{image('stars')}</a><br/>
{image('dial')}
</td>
</tr></table>

<details>
<summary>소개 · 기술 스택 · 링크를 텍스트로 보기</summary>

**Think with your code! — EXID-Developer**

Java와 Spring으로 서버를 세우고, React로 화면을 그리며, Spring AI로 새로운 가능성을 실험합니다.

- **Backend:** Java · Spring Boot · MyBatis
- **Frontend:** TypeScript · React · Vite
- **AI & Tools:** Spring AI · Git
- [GitHub]({U}) · [Repositories]({U}?tab=repositories) · [Stars]({U}?tab=stars)

</details>

### Activity

<p align="center">
<a href="https://streak-stats.demolab.com?user={OWNER}"><img src="./assets/porsche/activity.svg" width="49%" alt="Contribution snapshot from supplied screenshot, 2026-10-06: total 114, current streak 1, longest streak 5. Click for live stats."/></a>
<img src="./assets/porsche/languages.svg" width="49%" alt="Most used languages: Java 53.76%, TypeScript 30.41%, Python 13.09%, HTML 2.30%, CSS 0.36%, JavaScript 0.09%. Snapshot 2026-10-06."/>
</p>

<details>
<summary>Contribution trail</summary>
<p align="center"><img src="https://raw.githubusercontent.com/{OWNER}/{OWNER}/output/snake-cyber.svg" width="100%" alt="Contribution snake"/></p>
</details>

<a name="projects"></a>

### Featured projects

<p align="center">{' '.join(pins[:2])}</p>
<p align="center">{' '.join(pins[2:])}</p>

[공부 기록]({U}/SpringAiBasic) · [진행 중인 프로젝트]({U}/damso)

{image('footer')}

<p align="center">{switches()}</p>

<p align="center"><a href="./CREDITS.md">Credits · 이미지 출처</a> · <a href="./PORSCHE_THEME.md">Porsche 이미지·영상 제작 방식</a></p>

<p align="center"><sub>Theme switch: 저장소 소유자가 이슈를 제출하면 테마가 변경됩니다.</sub></p>
'''
 (ROOT/'README.md').write_text(s,encoding='utf-8')
 print('README.md rendered (porsche)')
if __name__=='__main__':build()
